# Generated by Django 3.2.16 on 2023-09-20 07:59

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], default='M', max_length=2, null=True)),
                ('lieu_de_naissance', models.CharField(blank=True, default='Lubumbashi', max_length=50, null=True)),
                ('date_de_naissance', models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True)),
                ('promotion', models.CharField(blank=True, default='Genie logiciel', max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en cours', 'en cours'), ('rejeter', 'rejeter'), ('approuver', 'approuver')], default='en cours', max_length=100)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('promotion', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeStage',
            fields=[
                ('documentacademique_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etudiant.documentacademique')),
                ('name', models.CharField(default='demande de stage', max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('destinateur', models.CharField(max_length=100)),
                ('entreprise', models.CharField(max_length=200)),
            ],
            bases=('etudiant.documentacademique',),
        ),
        migrations.CreateModel(
            name='ReleveCote',
            fields=[
                ('documentacademique_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etudiant.documentacademique')),
                ('photo_passport', models.FileField(upload_to='releveCote/')),
                ('nom_postnom_pere', models.CharField(blank=True, max_length=300, null=True)),
                ('nom_postnom_mere', models.CharField(blank=True, max_length=300, null=True)),
                ('telephone', models.CharField(max_length=14)),
            ],
            bases=('etudiant.documentacademique',),
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('message', models.CharField(max_length=1000000)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('information', 'information'), ('important', 'important'), ('urgent', 'urgent')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(max_length=5000)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParcousEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(choices=[('Preparatoire', 'Preparatoire'), ('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3')], max_length=100)),
                ('annee_academeique', models.CharField(max_length=100)),
                ('session_reussite', models.CharField(choices=[('premiere session', 'premiere session'), ('deuxieme session', 'deuxieme session')], max_length=100)),
                ('session_defense', models.CharField(blank=True, max_length=100, null=True)),
                ('filiere', models.CharField(blank=True, max_length=40, null=True)),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.relevecote')),
            ],
        ),
    ]
